/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesterFiolesRouteImport } from './routes/tester-fioles'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as EtudesScientifiquesRouteImport } from './routes/etudes-scientifiques'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CalculatriceRouteImport } from './routes/calculatrice'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as ProduitsSlugRouteImport } from './routes/produits.$slug'

const TesterFiolesRoute = TesterFiolesRouteImport.update({
  id: '/tester-fioles',
  path: '/tester-fioles',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudesScientifiquesRoute = EtudesScientifiquesRouteImport.update({
  id: '/etudes-scientifiques',
  path: '/etudes-scientifiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatriceRoute = CalculatriceRouteImport.update({
  id: '/calculatrice',
  path: '/calculatrice',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/etudes-scientifiques': typeof EtudesScientifiquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tester-fioles': typeof TesterFiolesRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/etudes-scientifiques': typeof EtudesScientifiquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tester-fioles': typeof TesterFiolesRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/produits': typeof ProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/etudes-scientifiques': typeof EtudesScientifiquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tester-fioles': typeof TesterFiolesRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/calculatrice'
    | '/cgv'
    | '/contact'
    | '/etudes-scientifiques'
    | '/mentions-legales'
    | '/panier'
    | '/sitemap.xml'
    | '/tester-fioles'
    | '/produits/$slug'
    | '/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/calculatrice'
    | '/cgv'
    | '/contact'
    | '/etudes-scientifiques'
    | '/mentions-legales'
    | '/panier'
    | '/sitemap.xml'
    | '/tester-fioles'
    | '/produits/$slug'
    | '/produits'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/calculatrice'
    | '/cgv'
    | '/contact'
    | '/etudes-scientifiques'
    | '/mentions-legales'
    | '/panier'
    | '/sitemap.xml'
    | '/tester-fioles'
    | '/produits/$slug'
    | '/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CalculatriceRoute: typeof CalculatriceRoute
  CgvRoute: typeof CgvRoute
  ContactRoute: typeof ContactRoute
  EtudesScientifiquesRoute: typeof EtudesScientifiquesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PanierRoute: typeof PanierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TesterFiolesRoute: typeof TesterFiolesRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tester-fioles': {
      id: '/tester-fioles'
      path: '/tester-fioles'
      fullPath: '/tester-fioles'
      preLoaderRoute: typeof TesterFiolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudes-scientifiques': {
      id: '/etudes-scientifiques'
      path: '/etudes-scientifiques'
      fullPath: '/etudes-scientifiques'
      preLoaderRoute: typeof EtudesScientifiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculatrice': {
      id: '/calculatrice'
      path: '/calculatrice'
      fullPath: '/calculatrice'
      preLoaderRoute: typeof CalculatriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CalculatriceRoute: CalculatriceRoute,
  CgvRoute: CgvRoute,
  ContactRoute: ContactRoute,
  EtudesScientifiquesRoute: EtudesScientifiquesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PanierRoute: PanierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TesterFiolesRoute: TesterFiolesRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
