/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TesterFiolesRouteImport } from './routes/tester-fioles'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProcessFabricationRouteImport } from './routes/process-fabrication'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LotRouteImport } from './routes/lot'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EtudesScientifiquesRouteImport } from './routes/etudes-scientifiques'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComparateurRouteImport } from './routes/comparateur'
import { Route as CoaRouteImport } from './routes/coa'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CalculatriceRouteImport } from './routes/calculatrice'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProduitsSlugRouteImport } from './routes/produits.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminStocksRouteImport } from './routes/admin.stocks'
import { Route as AdminSiteWebRouteImport } from './routes/admin.site-web'
import { Route as AdminSavRouteImport } from './routes/admin.sav'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AuthenticatedMonCompteIndexRouteImport } from './routes/_authenticated/mon-compte.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicPeptidepayWebhookRouteImport } from './routes/api/public/peptidepay-webhook'
import { Route as ApiPublicPaymentReminderRouteImport } from './routes/api/public/payment-reminder'
import { Route as ApiPublicCryptoWatcherRouteImport } from './routes/api/public/crypto-watcher'
import { Route as AuthenticatedMonCompteProfilRouteImport } from './routes/_authenticated/mon-compte.profil'
import { Route as AuthenticatedMonCompteContactRouteImport } from './routes/_authenticated/mon-compte.contact'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPushVapidKeyRouteImport } from './routes/api/public/push.vapid-key'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TesterFiolesRoute = TesterFiolesRouteImport.update({
  id: '/tester-fioles',
  path: '/tester-fioles',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessFabricationRoute = ProcessFabricationRouteImport.update({
  id: '/process-fabrication',
  path: '/process-fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LotRoute = LotRouteImport.update({
  id: '/lot',
  path: '/lot',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudesScientifiquesRoute = EtudesScientifiquesRouteImport.update({
  id: '/etudes-scientifiques',
  path: '/etudes-scientifiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparateurRoute = ComparateurRouteImport.update({
  id: '/comparateur',
  path: '/comparateur',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaRoute = CoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatriceRoute = CalculatriceRouteImport.update({
  id: '/calculatrice',
  path: '/calculatrice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteWebRoute = AdminSiteWebRouteImport.update({
  id: '/site-web',
  path: '/site-web',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSavRoute = AdminSavRouteImport.update({
  id: '/sav',
  path: '/sav',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonCompteIndexRoute =
  AuthenticatedMonCompteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMonCompteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPeptidepayWebhookRoute =
  ApiPublicPeptidepayWebhookRouteImport.update({
    id: '/api/public/peptidepay-webhook',
    path: '/api/public/peptidepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentReminderRoute =
  ApiPublicPaymentReminderRouteImport.update({
    id: '/api/public/payment-reminder',
    path: '/api/public/payment-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCryptoWatcherRoute = ApiPublicCryptoWatcherRouteImport.update({
  id: '/api/public/crypto-watcher',
  path: '/api/public/crypto-watcher',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMonCompteProfilRoute =
  AuthenticatedMonCompteProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedMonCompteRoute,
  } as any)
const AuthenticatedMonCompteContactRoute =
  AuthenticatedMonCompteContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedMonCompteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushVapidKeyRoute = ApiPublicPushVapidKeyRouteImport.update({
  id: '/api/public/push/vapid-key',
  path: '/api/public/push/vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/coa': typeof CoaRoute
  '/comparateur': typeof ComparateurRoute
  '/contact': typeof ContactRoute
  '/etudes-scientifiques': typeof EtudesScientifiquesRoute
  '/faq': typeof FaqRoute
  '/lot': typeof LotRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/panier': typeof PanierRoute
  '/process-fabrication': typeof ProcessFabricationRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tester-fioles': typeof TesterFiolesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/mon-compte': typeof AuthenticatedMonCompteRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/sav': typeof AdminSavRoute
  '/admin/site-web': typeof AdminSiteWebRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/mon-compte/contact': typeof AuthenticatedMonCompteContactRoute
  '/mon-compte/profil': typeof AuthenticatedMonCompteProfilRoute
  '/api/public/crypto-watcher': typeof ApiPublicCryptoWatcherRoute
  '/api/public/payment-reminder': typeof ApiPublicPaymentReminderRoute
  '/api/public/peptidepay-webhook': typeof ApiPublicPeptidepayWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/mon-compte/': typeof AuthenticatedMonCompteIndexRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRouteWithChildren
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/coa': typeof CoaRoute
  '/comparateur': typeof ComparateurRoute
  '/contact': typeof ContactRoute
  '/etudes-scientifiques': typeof EtudesScientifiquesRoute
  '/faq': typeof FaqRoute
  '/lot': typeof LotRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/panier': typeof PanierRoute
  '/process-fabrication': typeof ProcessFabricationRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tester-fioles': typeof TesterFiolesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/sav': typeof AdminSavRoute
  '/admin/site-web': typeof AdminSiteWebRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/mon-compte/contact': typeof AuthenticatedMonCompteContactRoute
  '/mon-compte/profil': typeof AuthenticatedMonCompteProfilRoute
  '/api/public/crypto-watcher': typeof ApiPublicCryptoWatcherRoute
  '/api/public/payment-reminder': typeof ApiPublicPaymentReminderRoute
  '/api/public/peptidepay-webhook': typeof ApiPublicPeptidepayWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/mon-compte': typeof AuthenticatedMonCompteIndexRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/calculatrice': typeof CalculatriceRoute
  '/cgv': typeof CgvRoute
  '/coa': typeof CoaRoute
  '/comparateur': typeof ComparateurRoute
  '/contact': typeof ContactRoute
  '/etudes-scientifiques': typeof EtudesScientifiquesRoute
  '/faq': typeof FaqRoute
  '/lot': typeof LotRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/panier': typeof PanierRoute
  '/process-fabrication': typeof ProcessFabricationRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tester-fioles': typeof TesterFiolesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/sav': typeof AdminSavRoute
  '/admin/site-web': typeof AdminSiteWebRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/_authenticated/mon-compte/contact': typeof AuthenticatedMonCompteContactRoute
  '/_authenticated/mon-compte/profil': typeof AuthenticatedMonCompteProfilRoute
  '/api/public/crypto-watcher': typeof ApiPublicCryptoWatcherRoute
  '/api/public/payment-reminder': typeof ApiPublicPaymentReminderRoute
  '/api/public/peptidepay-webhook': typeof ApiPublicPeptidepayWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/mon-compte/': typeof AuthenticatedMonCompteIndexRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/calculatrice'
    | '/cgv'
    | '/coa'
    | '/comparateur'
    | '/contact'
    | '/etudes-scientifiques'
    | '/faq'
    | '/lot'
    | '/mentions-legales'
    | '/offres'
    | '/panier'
    | '/process-fabrication'
    | '/quiz'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/tester-fioles'
    | '/unsubscribe'
    | '/mon-compte'
    | '/admin/clients'
    | '/admin/paiements'
    | '/admin/sav'
    | '/admin/site-web'
    | '/admin/stocks'
    | '/auth/callback'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/produits/$slug'
    | '/admin/'
    | '/blog/'
    | '/produits/'
    | '/mon-compte/contact'
    | '/mon-compte/profil'
    | '/api/public/crypto-watcher'
    | '/api/public/payment-reminder'
    | '/api/public/peptidepay-webhook'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/mon-compte/'
    | '/api/public/push/vapid-key'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/calculatrice'
    | '/cgv'
    | '/coa'
    | '/comparateur'
    | '/contact'
    | '/etudes-scientifiques'
    | '/faq'
    | '/lot'
    | '/mentions-legales'
    | '/offres'
    | '/panier'
    | '/process-fabrication'
    | '/quiz'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/tester-fioles'
    | '/unsubscribe'
    | '/admin/clients'
    | '/admin/paiements'
    | '/admin/sav'
    | '/admin/site-web'
    | '/admin/stocks'
    | '/auth/callback'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/produits/$slug'
    | '/admin'
    | '/blog'
    | '/produits'
    | '/mon-compte/contact'
    | '/mon-compte/profil'
    | '/api/public/crypto-watcher'
    | '/api/public/payment-reminder'
    | '/api/public/peptidepay-webhook'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/mon-compte'
    | '/api/public/push/vapid-key'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/calculatrice'
    | '/cgv'
    | '/coa'
    | '/comparateur'
    | '/contact'
    | '/etudes-scientifiques'
    | '/faq'
    | '/lot'
    | '/mentions-legales'
    | '/offres'
    | '/panier'
    | '/process-fabrication'
    | '/quiz'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/tester-fioles'
    | '/unsubscribe'
    | '/_authenticated/mon-compte'
    | '/admin/clients'
    | '/admin/paiements'
    | '/admin/sav'
    | '/admin/site-web'
    | '/admin/stocks'
    | '/auth/callback'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/produits/$slug'
    | '/admin/'
    | '/blog/'
    | '/produits/'
    | '/_authenticated/mon-compte/contact'
    | '/_authenticated/mon-compte/profil'
    | '/api/public/crypto-watcher'
    | '/api/public/payment-reminder'
    | '/api/public/peptidepay-webhook'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/_authenticated/mon-compte/'
    | '/api/public/push/vapid-key'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CalculatriceRoute: typeof CalculatriceRoute
  CgvRoute: typeof CgvRoute
  CoaRoute: typeof CoaRoute
  ComparateurRoute: typeof ComparateurRoute
  ContactRoute: typeof ContactRoute
  EtudesScientifiquesRoute: typeof EtudesScientifiquesRoute
  FaqRoute: typeof FaqRoute
  LotRoute: typeof LotRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OffresRoute: typeof OffresRoute
  PanierRoute: typeof PanierRoute
  ProcessFabricationRoute: typeof ProcessFabricationRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TesterFiolesRoute: typeof TesterFiolesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
  ApiPublicCryptoWatcherRoute: typeof ApiPublicCryptoWatcherRoute
  ApiPublicPaymentReminderRoute: typeof ApiPublicPaymentReminderRoute
  ApiPublicPeptidepayWebhookRoute: typeof ApiPublicPeptidepayWebhookRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPushVapidKeyRoute: typeof ApiPublicPushVapidKeyRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tester-fioles': {
      id: '/tester-fioles'
      path: '/tester-fioles'
      fullPath: '/tester-fioles'
      preLoaderRoute: typeof TesterFiolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-fabrication': {
      id: '/process-fabrication'
      path: '/process-fabrication'
      fullPath: '/process-fabrication'
      preLoaderRoute: typeof ProcessFabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot': {
      id: '/lot'
      path: '/lot'
      fullPath: '/lot'
      preLoaderRoute: typeof LotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudes-scientifiques': {
      id: '/etudes-scientifiques'
      path: '/etudes-scientifiques'
      fullPath: '/etudes-scientifiques'
      preLoaderRoute: typeof EtudesScientifiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparateur': {
      id: '/comparateur'
      path: '/comparateur'
      fullPath: '/comparateur'
      preLoaderRoute: typeof ComparateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa': {
      id: '/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof CoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculatrice': {
      id: '/calculatrice'
      path: '/calculatrice'
      fullPath: '/calculatrice'
      preLoaderRoute: typeof CalculatriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/stocks': {
      id: '/admin/stocks'
      path: '/stocks'
      fullPath: '/admin/stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-web': {
      id: '/admin/site-web'
      path: '/site-web'
      fullPath: '/admin/site-web'
      preLoaderRoute: typeof AdminSiteWebRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sav': {
      id: '/admin/sav'
      path: '/sav'
      fullPath: '/admin/sav'
      preLoaderRoute: typeof AdminSavRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte/': {
      id: '/_authenticated/mon-compte/'
      path: '/'
      fullPath: '/mon-compte/'
      preLoaderRoute: typeof AuthenticatedMonCompteIndexRouteImport
      parentRoute: typeof AuthenticatedMonCompteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/peptidepay-webhook': {
      id: '/api/public/peptidepay-webhook'
      path: '/api/public/peptidepay-webhook'
      fullPath: '/api/public/peptidepay-webhook'
      preLoaderRoute: typeof ApiPublicPeptidepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-reminder': {
      id: '/api/public/payment-reminder'
      path: '/api/public/payment-reminder'
      fullPath: '/api/public/payment-reminder'
      preLoaderRoute: typeof ApiPublicPaymentReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crypto-watcher': {
      id: '/api/public/crypto-watcher'
      path: '/api/public/crypto-watcher'
      fullPath: '/api/public/crypto-watcher'
      preLoaderRoute: typeof ApiPublicCryptoWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mon-compte/profil': {
      id: '/_authenticated/mon-compte/profil'
      path: '/profil'
      fullPath: '/mon-compte/profil'
      preLoaderRoute: typeof AuthenticatedMonCompteProfilRouteImport
      parentRoute: typeof AuthenticatedMonCompteRoute
    }
    '/_authenticated/mon-compte/contact': {
      id: '/_authenticated/mon-compte/contact'
      path: '/contact'
      fullPath: '/mon-compte/contact'
      preLoaderRoute: typeof AuthenticatedMonCompteContactRouteImport
      parentRoute: typeof AuthenticatedMonCompteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/vapid-key': {
      id: '/api/public/push/vapid-key'
      path: '/api/public/push/vapid-key'
      fullPath: '/api/public/push/vapid-key'
      preLoaderRoute: typeof ApiPublicPushVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMonCompteRouteChildren {
  AuthenticatedMonCompteContactRoute: typeof AuthenticatedMonCompteContactRoute
  AuthenticatedMonCompteProfilRoute: typeof AuthenticatedMonCompteProfilRoute
  AuthenticatedMonCompteIndexRoute: typeof AuthenticatedMonCompteIndexRoute
}

const AuthenticatedMonCompteRouteChildren: AuthenticatedMonCompteRouteChildren =
  {
    AuthenticatedMonCompteContactRoute: AuthenticatedMonCompteContactRoute,
    AuthenticatedMonCompteProfilRoute: AuthenticatedMonCompteProfilRoute,
    AuthenticatedMonCompteIndexRoute: AuthenticatedMonCompteIndexRoute,
  }

const AuthenticatedMonCompteRouteWithChildren =
  AuthenticatedMonCompteRoute._addFileChildren(
    AuthenticatedMonCompteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminSavRoute: typeof AdminSavRoute
  AdminSiteWebRoute: typeof AdminSiteWebRoute
  AdminStocksRoute: typeof AdminStocksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminSavRoute: AdminSavRoute,
  AdminSiteWebRoute: AdminSiteWebRoute,
  AdminStocksRoute: AdminStocksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CalculatriceRoute: CalculatriceRoute,
  CgvRoute: CgvRoute,
  CoaRoute: CoaRoute,
  ComparateurRoute: ComparateurRoute,
  ContactRoute: ContactRoute,
  EtudesScientifiquesRoute: EtudesScientifiquesRoute,
  FaqRoute: FaqRoute,
  LotRoute: LotRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OffresRoute: OffresRoute,
  PanierRoute: PanierRoute,
  ProcessFabricationRoute: ProcessFabricationRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TesterFiolesRoute: TesterFiolesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
  ApiPublicCryptoWatcherRoute: ApiPublicCryptoWatcherRoute,
  ApiPublicPaymentReminderRoute: ApiPublicPaymentReminderRoute,
  ApiPublicPeptidepayWebhookRoute: ApiPublicPeptidepayWebhookRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPushVapidKeyRoute: ApiPublicPushVapidKeyRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
